# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kcrash': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kiconthemes': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/knewstuff': '@stable'
    'frameworks/kplotting': '@stable'
    'frameworks/ktextwidgets': '@stable'
    'frameworks/kdoctools': '@stable'
